name: Testing & Publish
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: pnpm install
      - name: Building & Testing
        run: pnpm test

  publish:
    runs-on: ubuntu-latest
    needs: testing
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: pnpm install
      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
