name: Testing
on:
  push:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: pnpm install
      - name: Building & Testing
        run: pnpm test
        env:
          TABLES_SHEET_ID: ${{ secrets.TABLES_SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
